### ISSUE TITLE
unable to import a .dae , 'SPICA.PICA.Converters.PICAVertex' was not present in the dictionary.

### ISSUE THREAD

**Issue by Icing-weaponry** [MapStudioProject/CTR-Studio#21]
Hi there,

let me preface by saying I'm a complete n00b in 3d.

I made a model that works using the old version of spica and I can import in game with no problem but I wanted to use CRT studio to possibly learn to do it with better tools.

I made the [following .DAE file](https://u.pcloud.link/publink/show?code=XZwUPDVZgNKKRfEIzb0jABzFHhNOU8yhfEHX) using maya and when I try to "replace" the model in the bch file, I get the following error message.

`The given key 'SPICA.PICA.Converters.PICAVertex' was not present in the dictionary. 
   at CtrLibrary.Bch.BchModelImporter.<GenerateSubMeshes>g__UpdateVertex|5_2(Int32 ind, PICAVertex[]& vertices, <>c__DisplayClass5_0& , <>c__DisplayClass5_1& ) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\BchModelImporter.cs:line 479
   at CtrLibrary.Bch.BchModelImporter.GenerateSubMeshes(H3DModel gfxModel, IOMesh mesh, IOPolygon poly, Int32 skinningCount, Int32 singleBindIndex, PICAVertex[]& vertices, Int32 max_bones) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\BchModelImporter.cs:line 499
   at CtrLibrary.Bch.BchModelImporter.ConvertMesh(IOScene scene, IOMesh iomesh, H3DModel h3dModel, Matrix4x4[] skinningMatrices, CtrImportSettings settings) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\BchModelImporter.cs:line 263
   at CtrLibrary.Bch.BchModelImporter.Import(String filePath, BCH bchWrapper, H3DModel parent, CtrImportSettings settings) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\BchModelImporter.cs:line 173
   at CtrLibrary.Bch.CMDL.ImportFile(String filePath, CtrImportSettings settings) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\ModelWrapper.cs:line 331
   at CtrLibrary.Bch.CMDL.<>c__DisplayClass20_0.<Replace>b__1(Boolean o) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\ModelWrapper.cs:line 300`

I was wondering if that was an error with the software since it mentions a missing dictionary.

thank you in advance for your help

**Comment by Icing-weaponry** [comment]
nevermind that, I started using blender, cleaned up my model and follow the steps in the discord more closely and now it works.
You can close this thread, thank you
