### ISSUE TITLE
Issues with importing certain .dae models

### ISSUE THREAD

**Issue by RocketRobz** [MapStudioProject/CTR-Studio#41]
After creating a new .bch file, and right-clicking the `Models` directory and then clicking `Import` to import one of the below models, the following errors occur.

https://www.models-resource.com/ds_dsi/supermario64ds/model/22818/
```
Object reference not set to an instance of an object. 
   at IONET.Collada.ColladaImporter.LoadGeometryControllerFromID(Node n, String id)
   at IONET.Collada.ColladaImporter.LoadNodes(Node n, IOBone parent, Matrix4x4 parentMatrix, IOModel model, List1 skeletonIds)
   at IONET.Collada.ColladaImporter.GetScene(String filePath)
   at IONET.IOManager.LoadScene(String filePath, ImportSettings settings)
   at CtrLibrary.Bch.BchModelImporter.Import(String filePath, BCH bchWrapper, H3DModel parent, CtrImportSettings settings) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\BchModelImporter.cs:line 27
   at CtrLibrary.Bch.CMDL1.ImportFile(String filePath, CtrImportSettings settings) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\ModelWrapper.cs:line 381
   at CtrLibrary.Bch.ModelFolder1.<>c__DisplayClass10_0.<Import>b__1(Boolean o) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\ModelWrapper.cs:line 124
```

https://www.models-resource.com/wii/supersmashbrosbrawl/model/7042/
```
There is an error in XML document (2, 2). 
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at IONET.Collada.Collada.LoadFromFile(String fileName)
   at IONET.Collada.ColladaImporter.GetScene(String filePath)
   at IONET.IOManager.LoadScene(String filePath, ImportSettings settings)
   at CtrLibrary.Bch.BchModelImporter.Import(String filePath, BCH bchWrapper, H3DModel parent, CtrImportSettings settings) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\BchModelImporter.cs:line 27
   at CtrLibrary.Bch.CMDL1.ImportFile(String filePath, CtrImportSettings settings) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\ModelWrapper.cs:line 381
   at CtrLibrary.Bch.ModelFolder1.<>c__DisplayClass10_0.<Import>b__1(Boolean o) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\ModelWrapper.cs:line 124
```

https://www.models-resource.com/3ds/thelegendofzeldaocarinaoftime3d/model/13562/
```
Index was outside the bounds of the array. 
   at IONET.Collada.ColladaImporter.LoadGeometryFromID(Node n, String id, List1 vertexEnvelopes)
   at IONET.Collada.ColladaImporter.LoadNodes(Node n, IOBone parent, Matrix4x4 parentMatrix, IOModel model, List1 skeletonIds)
   at IONET.Collada.ColladaImporter.GetScene(String filePath)
   at IONET.IOManager.LoadScene(String filePath, ImportSettings settings)
   at CtrLibrary.Bch.BchModelImporter.Import(String filePath, BCH bchWrapper, H3DModel parent, CtrImportSettings settings) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\BchModelImporter.cs:line 27
   at CtrLibrary.Bch.CMDL1.ImportFile(String filePath, CtrImportSettings settings) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\ModelWrapper.cs:line 381
   at CtrLibrary.Bch.ModelFolder1.<>c__DisplayClass10_0.<Import>b__1(Boolean o) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\ModelWrapper.cs:line 124
```

**Comment by KillzXGaming** [comment]
Some of those files are incorrectly made, and some just have export issues in general. If you import them into a 3D program like blender, then export as .dae, they should work fine. You'll more than likely need to use a 3D program like blender to properly resize and adjust for the game it is importing over anyways.

**Comment by RocketRobz** [comment]
Thanks for the tip!
