### ISSUE TITLE
[Aikatsu] Animations wont export to .anim (Unsupported primitive type! Vector3D)

### ISSUE THREAD

**Issue by Sozuke** [MapStudioProject/CTR-Studio#45]
sample file 
[L_DollyD_00.zip](https://github.com/MapStudioProject/CTR-Studio/files/12902695/L_DollyD_00.zip)

log:

> Unhandled exception. System.Exception: Unsupported primitive type! Vector3D
   at CtrLibrary.BchSkelAnimationImporter.Export(H3DAnimation gfxAnimation, H3DModel model, String filePath) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\BchSkelAnimationImporter.cs:line 61
   at CtrLibrary.Bch.BCH.AnimationNode`1.Export(String filePath) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\BCH.cs:line 602
   at CtrLibrary.Bch.BCH.NodeSection`1.ExportDialog() in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCH\BCH.cs:line 857
   at Toolbox.Core.ViewModels.CommandViewModel.Execute(Object o) in C:\projects\ctr-studio\Toolbox.Core\src\ViewModels\CommandViewModel.cs:line 17
   at MapStudio.UI.ImGuiHelper.<>c__DisplayClass7_0.<LoadMenuItem>b__0() in C:\projects\ctr-studio\MapStudio.UI\src\Imgui\Helpers\ImGuiHelper.cs:line 119
   at UIFramework.Framework.OnRenderFrame(FrameEventArgs e) in C:\projects\ctr-studio\MapStudio.UI\src\UIFramework\Framework.cs:line 84
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at OpenTK.GameWindow.Run()
   at CTRStudio.Program.Main(String[] args) in C:\projects\ctr-studio\CTR Studio\src\Program.cs:line 53

**Comment by Sozuke** [comment]
This happens with both skeletal and camera animations

**Comment by KillzXGaming** [comment]
Fixed as of https://github.com/MapStudioProject/CTR-Studio/commit/4a16956855e7506c797f29725cbc6f32f01d6c96
