### ISSUE TITLE
FBX Import doesn't work

### ISSUE THREAD

**Issue by DahniMae** [MapStudioProject/CTR-Studio#62]
Program fails to import fbx files at all

i jsut get an error that says:
Compressed data has invalid checksum, near offset 67810
Details copied to clipboard

**Comment by DahniMae** [comment]
and the clipboard details are:
Compressed data has invalid checksum, near offset 67810 
   at IONET.Fbx.IO.FbxBinaryReader.ReadArray(ReadPrimitive readPrimitive, Type arrayType) in C:\projects\ctr-studio\IONET\IONET\Fbx\IO\FbxBinaryReader.cs:line 146
   at IONET.Fbx.IO.FbxBinaryReader.ReadProperty() in C:\projects\ctr-studio\IONET\IONET\Fbx\IO\FbxBinaryReader.cs:line 57
   at IONET.Fbx.IO.FbxBinaryReader.ReadNode(Int32 version) in C:\projects\ctr-studio\IONET\IONET\Fbx\IO\FbxBinaryReader.cs:line 187
   at IONET.Fbx.IO.FbxBinaryReader.ReadNode(Int32 version) in C:\projects\ctr-studio\IONET\IONET\Fbx\IO\FbxBinaryReader.cs:line 204
   at IONET.Fbx.IO.FbxBinaryReader.ReadNode(Int32 version) in C:\projects\ctr-studio\IONET\IONET\Fbx\IO\FbxBinaryReader.cs:line 204
   at IONET.Fbx.IO.FbxBinaryReader.Read() in C:\projects\ctr-studio\IONET\IONET\Fbx\IO\FbxBinaryReader.cs:line 230
   at IONET.Fbx.FbxIO.ReadBinary(String path) in C:\projects\ctr-studio\IONET\IONET\Fbx\FbxIO.cs:line 26
   at IONET.Fbx.FbxImporter.GetScene(String filePath) in C:\projects\ctr-studio\IONET\IONET\Fbx\FbxImporter.cs:line 17
   at IONET.IOManager.LoadScene(String filePath, ImportSettings settings) in C:\projects\ctr-studio\IONET\IONET\IOManager.cs:line 104
   at CtrLibrary.Bcres.BcresModelImporter.Import(String filePath, BCRES bcresWrapper, GfxModel parent, CtrImportSettings settings) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCRES\BcresModelImporter.cs:line 27
   at CtrLibrary.Bcres.CMDL.ImportFile(String filePath, CtrImportSettings settings) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCRES\ModelWrapper.cs:line 398
   at CtrLibrary.Bcres.ModelFolder.<>c__DisplayClass6_0.<Import>b__1(Boolean o) in C:\projects\ctr-studio\Plugins\CtrLibrary\Files\BCRES\ModelWrapper.cs:line 92
