### ISSUE TITLE
Opening .bcmdl for custom track results in crash

### ISSUE THREAD

**Issue by ScottyBody8** [MapStudioProject/CTR-Studio#8]
The .bcmdl I am trying to open in CTR-Studio is for a MarioKart 7 custom track and it has no issues opening in Every File Explorer and running on 3DS hardware. However trying to open the file in CTR-Studio to modify textures and animations results in a crash:

[Link to my BCMDL](https://drive.google.com/file/d/1SLgfQyV07s0NTfeHc7DJUGeOKsJXP0GN/view?usp=sharing)

Crash Log:
Value must be non-negative and less than or equal to Int32.MaxValue. (Parameter 'dstOffset')
    at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at SPICA.PICA.Converters.TextureCompression.ETC1Decompress(Byte[] Input, Int32 Width, Int32 Height, Boolean Alpha) in C:\Users\Nathan\source\repos\SPICA\SPICA\PICA\Converters\TextureCompression.cs:line 44
   at SPICA.PICA.Converters.TextureConverter.DecodeBuffer(Byte[] Input, Int32 Width, Int32 Height, PICATextureFormat Format) in C:\Users\Nathan\source\repos\SPICA\SPICA\PICA\Converters\TextureConverter.cs:line 32
   at SPICA.Formats.CtrH3D.Texture.H3DTexture.ToMipRGBA(Int32 level, Int32 Face) in C:\Users\Nathan\source\repos\SPICA\SPICA\Formats\CtrH3D\Texture\H3DTexture.cs:line 135
   at SPICA.Rendering.Texture..ctor(H3DTexture Texture) in C:\Users\Nathan\source\repos\SPICA\SPICA.Rendering\Texture.cs:line 66
   at SPICA.Rendering.Renderer.Merge(H3DDict`1 Textures) in C:\Users\Nathan\source\repos\SPICA\SPICA.Rendering\Renderer.cs:line 152
   at SPICA.Rendering.Renderer.Merge(H3D Scene) in C:\Users\Nathan\source\repos\SPICA\SPICA.Rendering\Renderer.cs:line 104
   at CtrLibrary.Rendering.H3DRender.Load(H3D h3d)
   at CtrLibrary.Rendering.H3DRender..ctor(H3D h3d, NodeBase parent)
   at CtrLibrary.Bcres.BCRES.Load(Gfx gfx)
   at CtrLibrary.Bcres.BCRES.Load(Stream stream)
   at Toolbox.Core.IO.STFileLoader.SetFileFormat(IFileFormat fileFormat, String FileName, Stream stream, Settings settings)
   at Toolbox.Core.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Settings settings)
   at Toolbox.Core.IO.STFileLoader.OpenFileFormat(String FileName, Settings settings)
   at MapStudio.UI.Workspace.LoadFileFormat(String filePath, Boolean isProject)
   at CTRStudio.MainWindow.LoadFileFormat(String filePath)
   at CTRStudio.MainWindow.OpenFileWithDialog()
   at UIFramework.MenuItem.Execute()
   at MapStudio.UI.ImGuiHelper.<>c__DisplayClass11_0.<DrawMenuItem>b__0()
   at UIFramework.Framework.OnRenderFrame(FrameEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at OpenTK.GameWindow.Run()
   at CTRStudio.Program.Main(String[] args)

**Comment by KillzXGaming** [comment]
The texture you have named "Material" does not have valid dimensions.  I'll add a check to skip broken textures

**Comment by KillzXGaming** [comment]
Should open as of https://github.com/MapStudioProject/CTR-Studio/commit/5e39eebe5b522fe1fcb42d431d77b038bc8f5d7e

**Comment by ScottyBody8** [comment]
Still getting a crash running latest software:

Value must be non-negative and less than or equal to Int32.MaxValue. (Parameter 'dstOffset')
    at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at SPICA.PICA.Converters.TextureCompression.ETC1Decompress(Byte[] Input, Int32 Width, Int32 Height, Boolean Alpha) in C:\Users\Nathan\source\repos\SPICA\SPICA\PICA\Converters\TextureCompression.cs:line 44
   at SPICA.PICA.Converters.TextureConverter.DecodeBuffer(Byte[] Input, Int32 Width, Int32 Height, PICATextureFormat Format) in C:\Users\Nathan\source\repos\SPICA\SPICA\PICA\Converters\TextureConverter.cs:line 32
   at SPICA.Formats.CtrH3D.Texture.H3DTexture.ToMipRGBA(Int32 level, Int32 Face) in C:\Users\Nathan\source\repos\SPICA\SPICA\Formats\CtrH3D\Texture\H3DTexture.cs:line 135
   at SPICA.Rendering.Texture..ctor(H3DTexture Texture) in C:\Users\Nathan\source\repos\SPICA\SPICA.Rendering\Texture.cs:line 66
   at SPICA.Rendering.Renderer.Merge(H3DDict`1 Textures) in C:\Users\Nathan\source\repos\SPICA\SPICA.Rendering\Renderer.cs:line 152
   at SPICA.Rendering.Renderer.Merge(H3D Scene) in C:\Users\Nathan\source\repos\SPICA\SPICA.Rendering\Renderer.cs:line 104
   at CtrLibrary.Rendering.H3DRender.Load(H3D h3d)
   at CtrLibrary.Rendering.H3DRender..ctor(H3D h3d, NodeBase parent)
   at CtrLibrary.Bcres.BCRES.Load(Gfx gfx)
   at CtrLibrary.Bcres.BCRES.Load(Stream stream)
   at Toolbox.Core.IO.STFileLoader.SetFileFormat(IFileFormat fileFormat, String FileName, Stream stream, Settings settings)
   at Toolbox.Core.IO.STFileLoader.OpenFileFormat(Stream stream, String FileName, Settings settings)
   at Toolbox.Core.IO.STFileLoader.OpenFileFormat(String FileName, Settings settings)
   at MapStudio.UI.Workspace.LoadFileFormat(String filePath, Boolean isProject)
   at CTRStudio.MainWindow.LoadFileFormat(String filePath)
   at CTRStudio.MainWindow.OpenFileWithDialog()
   at UIFramework.MenuItem.Execute()
   at MapStudio.UI.ImGuiHelper.<>c__DisplayClass11_0.<DrawMenuItem>b__0()
   at UIFramework.Framework.OnRenderFrame(FrameEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at OpenTK.GameWindow.Run()
   at CTRStudio.Program.Main(String[] args)

**Comment by asfaew** [comment]
yeah i have the same issue except it doesnt crash, it does nothing
